/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c WM3000UDBusHelperAdapter -a dbushelperadapter.h:dbushelperadapter.cpp de.zera.wm3000u.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbushelperadapter.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class WM3000UDBusHelperAdapter
 */

WM3000UDBusHelperAdapter::WM3000UDBusHelperAdapter(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

WM3000UDBusHelperAdapter::~WM3000UDBusHelperAdapter()
{
    // destructor
}

bool WM3000UDBusHelperAdapter::isVisible(const QString &widgetName)
{
    // handle method call de.zera.WM3000UDBusHelper.isVisible
    bool out0;
    QMetaObject::invokeMethod(parent(), "isVisible", Q_RETURN_ARG(bool, out0), Q_ARG(QString, widgetName));
    return out0;
}

void WM3000UDBusHelperAdapter::setVisible(const QString &widgetName, bool visibility)
{
    // handle method call de.zera.WM3000UDBusHelper.setVisible
    QMetaObject::invokeMethod(parent(), "setVisible", Q_ARG(QString, widgetName), Q_ARG(bool, visibility));
}

